# Games

The following notebook contains an ETL process to which a file containing data from the video games platform STEAM was subjected. The file contains information about different products available in the STEAM platform, such as: publisher, name, release date, tags, etc.

In [232]:
#Needed_Libraries

import pandas as pd
import numpy as np
import json
import re
from etl_functions import general_information, get_year, column_comparator

In [233]:
df_games=pd.read_json("data/output_steam_games.json", lines=True)

In [234]:
df_games.head(5)

  publisher genres app_name title   url  ... specs price early_access  id developer
0      None   None     None  None  None  ...  None  None          NaN NaN      None
1      None   None     None  None  None  ...  None  None          NaN NaN      None
2      None   None     None  None  None  ...  None  None          NaN NaN      None
3      None   None     None  None  None  ...  None  None          NaN NaN      None
4      None   None     None  None  None  ...  None  None          NaN NaN      None

[5 rows x 13 columns]

In [235]:
df_games.tail(5)

              publisher  ...                 developer
120440  Ghost_RUS Games  ...        Nikita "Ghost_RUS"
120441           Sacada  ...                    Sacada
120442     Laush Studio  ...  Laush Dmitriy Sergeevich
120443         SIXNAILS  ...             xropi,stev3ns
120444             None  ...                      None

[5 rows x 13 columns]

In [236]:
df_games.shape

(120445, 13)

In [237]:
general_information(df_games)

          column      data_type  missing_values  missing_values_percentage
0      publisher  <class 'str'>          192724                       1.60
1         genres  <class 'str'>          183186                       1.52
2       app_name  <class 'str'>          176624                       1.47
3          title  <class 'str'>          180720                       1.50
4            url  <class 'str'>          176620                       1.47
5   release_date  <class 'str'>          180754                       1.50
6           tags  <class 'str'>          176946                       1.47
7    reviews_url  <class 'str'>          176624                       1.47
8          specs  <class 'str'>          177960                       1.48
9          price  <class 'str'>          179374                       1.49
10  early_access  <class 'str'>           88310                       0.73
11            id  <class 'str'>           88312                       0.73
12     developer  <class 'str'>          183218                       1.52

Unfortunately many values in the dataframe are missing. Nevertheless, we have no way to fill these missing values and our only option is to drop them.

In [238]:
df_games.dropna(inplace=True)

In [239]:
general_information(df_games)

          column      data_type  missing_values  missing_values_percentage
0      publisher  <class 'str'>               0                        0.0
1         genres  <class 'str'>               0                        0.0
2       app_name  <class 'str'>               0                        0.0
3          title  <class 'str'>               0                        0.0
4            url  <class 'str'>               0                        0.0
5   release_date  <class 'str'>               0                        0.0
6           tags  <class 'str'>               0                        0.0
7    reviews_url  <class 'str'>               0                        0.0
8          specs  <class 'str'>               0                        0.0
9          price  <class 'str'>               0                        0.0
10  early_access  <class 'str'>               0                        0.0
11            id  <class 'str'>               0                        0.0
12     developer  <class 'str'>               0                        0.0

In [240]:
df_games.head(5)

                 publisher  ...            developer
88310            Kotoshiro  ...            Kotoshiro
88311     Making Fun, Inc.  ...     Secret Level SRL
88312         Poolians.com  ...         Poolians.com
88313                 彼岸领域  ...                 彼岸领域
88315  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 13 columns]

Now, we can proceed to remove useless columns.

In [241]:
df_games.drop(columns=["url","reviews_url"],inplace=True)

In [242]:
df_games.head(5)

                 publisher  ...            developer
88310            Kotoshiro  ...            Kotoshiro
88311     Making Fun, Inc.  ...     Secret Level SRL
88312         Poolians.com  ...         Poolians.com
88313                 彼岸领域  ...                 彼岸领域
88315  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 11 columns]

Intuitevely we can see that some of the columns store similar values. Since we don't want to process redundant data what we can do is to compare pairs of columns and determine the percentage of common values to both columns, and in that way we can decide which columns we need to keep and which columns we can remove.

In [243]:
df_games.reset_index(inplace=True)

In [244]:
df_games.head(5)

   index            publisher  ...        id            developer
0  88310            Kotoshiro  ...  761140.0            Kotoshiro
1  88311     Making Fun, Inc.  ...  643980.0     Secret Level SRL
2  88312         Poolians.com  ...  670290.0         Poolians.com
3  88313                 彼岸领域  ...  767400.0                 彼岸领域
4  88315  Trickjump Games Ltd  ...  772540.0  Trickjump Games Ltd

[5 rows x 12 columns]

In [245]:
df_games.drop(columns={"index"},inplace=True)

In [246]:
df_games.head(5)

             publisher  ...            developer
0            Kotoshiro  ...            Kotoshiro
1     Making Fun, Inc.  ...     Secret Level SRL
2         Poolians.com  ...         Poolians.com
3                 彼岸领域  ...                 彼岸领域
4  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 11 columns]

In [247]:
#Comparating columns
column_comparator(df_games,"app_name","title")

'The percentage of common values for the columns app_name and title is 97.44%'

Then, since the columns app name and title are very similar to each other (they contain pretty much the same values), we can drop one of them.

In [248]:
df_games.drop(columns={"title"},inplace=True)

In [249]:
df_games.head(5)

             publisher  ...            developer
0            Kotoshiro  ...            Kotoshiro
1     Making Fun, Inc.  ...     Secret Level SRL
2         Poolians.com  ...         Poolians.com
3                 彼岸领域  ...                 彼岸领域
4  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 10 columns]

In [250]:
column_comparator(df_games,"genres","tags")

'The percentage of common values for the columns genres and tags is 21.21%'

In [251]:
column_comparator(df_games,"tags","specs")

'The percentage of common values for the columns tags and specs is -1.0%'

In [252]:
column_comparator(df_games,"publisher","developer")

'The percentage of common values for the columns publisher and developer is 50.17%'

We see that for the rest of the columns, there are significant differences, so we can keep all of them. And now, we can apply the last necessary changes to the remaining data.

In [253]:
df_games.rename(columns={"id":"item_id"},inplace=True)

In [254]:
df_games.head(5)

             publisher  ...            developer
0            Kotoshiro  ...            Kotoshiro
1     Making Fun, Inc.  ...     Secret Level SRL
2         Poolians.com  ...         Poolians.com
3                 彼岸领域  ...                 彼岸领域
4  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 10 columns]

In [255]:
df_games["release_date"]=df_games["release_date"].apply(get_year)

In [256]:
df_games.head(5)

             publisher  ...            developer
0            Kotoshiro  ...            Kotoshiro
1     Making Fun, Inc.  ...     Secret Level SRL
2         Poolians.com  ...         Poolians.com
3                 彼岸领域  ...                 彼岸领域
4  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 10 columns]

In [257]:
df_games.rename(columns={"release_date":"release_year"},inplace=True)

In [258]:
df_games.head(5)

             publisher  ...            developer
0            Kotoshiro  ...            Kotoshiro
1     Making Fun, Inc.  ...     Secret Level SRL
2         Poolians.com  ...         Poolians.com
3                 彼岸领域  ...                 彼岸领域
4  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 10 columns]

In [259]:
df_games["item_id"]=df_games["item_id"].astype("int64")

In [260]:
df_games.head(5)

             publisher  ...            developer
0            Kotoshiro  ...            Kotoshiro
1     Making Fun, Inc.  ...     Secret Level SRL
2         Poolians.com  ...         Poolians.com
3                 彼岸领域  ...                 彼岸领域
4  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 10 columns]

In [261]:
df_games["early_access"]=df_games["early_access"].astype("int64")

In [262]:
df_games.head(5)

             publisher  ...            developer
0            Kotoshiro  ...            Kotoshiro
1     Making Fun, Inc.  ...     Secret Level SRL
2         Poolians.com  ...         Poolians.com
3                 彼岸领域  ...                 彼岸领域
4  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 10 columns]

In [263]:
df_games["price"].unique()

array([4.99, 'Free To Play', 'Free to Play', 0.99, 3.99, 18.99, 29.99,
       10.99, 2.99, 1.5899999999999999, 14.99, 1.99, 59.99, 9.99, 6.99,
       7.99, 39.99, 'Free', 19.99, 7.49, 8.99, 12.99, 5.99, 2.49, 15.99,
       1.25, 24.99, 17.99, 61.99, 3.49, 11.99, 13.99, 'Free Demo',
       'Play for Free!', 34.99, 1.49, 32.99, 99.99, 14.95, 69.99, 16.99,
       79.99, 49.99, 13.98, 149.99, 771.71, 'Install Now', 21.99, 89.99,
       'Play WARMACHINE: Tactics Demo', 0.98, 139.92, 4.29, 'Free Mod',
       54.99, 64.99, 74.99, 0.89, 0.5, 'Play Now', 299.99, 1.29, 119.99,
       44.99, 3.0, 15.0, 1.3900000000000001, 'Free HITMAN™ Holiday Pack',
       2.0, 4.0, 1.9500000000000002, 1.5, 6.66, 26.99, 399.99, 31.99,
       20.0, 40.0, 5.0, 3.33, 38.85, 71.7, 995.0, 5.49, 27.49, 3.39, 6.0,
       19.95, 20.99, 499.99, 27.99, 199.99, 4.68, 131.4, 44.98, 202.76,
       2.3, 0.9500000000000001, 36.99, 172.24, 249.99, 2.9699999999999998,
       10.96, 2.66, 6.48, 10.0, 1.0, 11.15, 'Play the Demo', 49.0, 199.0,
       99.0, 87.94, 0.49, 9.98, 9.95, 12.89, 6.49, 1.87, 41.99, 4.49,
       289.99, 23.96, 5.65, 12.0, 129.99, 23.99, 13.37, 189.96, 59.95,
       160.91, 'Third-party'], dtype=object)

In [264]:
df_games["price"]=df_games["price"].astype(str).str.replace(r'Free to Play','0',regex=True)

In [265]:
df_games.head(5)

             publisher  ...            developer
0            Kotoshiro  ...            Kotoshiro
1     Making Fun, Inc.  ...     Secret Level SRL
2         Poolians.com  ...         Poolians.com
3                 彼岸领域  ...                 彼岸领域
4  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 10 columns]

In [266]:
df_games["price"]=df_games["price"].astype(str).str.replace(r'Free To Play','0',regex=True)

In [267]:
df_games.head(5)

             publisher  ...            developer
0            Kotoshiro  ...            Kotoshiro
1     Making Fun, Inc.  ...     Secret Level SRL
2         Poolians.com  ...         Poolians.com
3                 彼岸领域  ...                 彼岸领域
4  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 10 columns]

In [268]:
df_games["price"]=df_games["price"].astype(str).str.replace(r'Play for Free!','0',regex=True)

In [269]:
df_games["price"]=df_games["price"].astype(str).str.replace(r'Free!','0',regex=True)

In [270]:
df_games["price"]=df_games["price"].astype(str).str.replace(r'Free','0',regex=True)

In [271]:
df_games["price"]=df_games["price"].astype(str).str.replace(r'Install Now','None',regex=True)
df_games["price"]=df_games["price"].astype(str).str.replace(r'Play WARMACHINE: Tactics Demo','None',regex=True)
df_games["price"]=df_games["price"].astype(str).str.replace(r'0 Demo','None',regex=True)
df_games["price"]=df_games["price"].astype(str).str.replace(r'0 HITMAN™ Holiday Pack','None',regex=True)
df_games["price"]=df_games["price"].astype(str).str.replace(r'Third-party','None',regex=True)
df_games["price"]=df_games["price"].astype(str).str.replace(r'Install Now','None',regex=True)
df_games["price"]=df_games["price"].astype(str).str.replace(r'Play the Demo','None',regex=True)
df_games["price"]=df_games["price"].astype(str).str.replace(r'0 Mod','None',regex=True)
df_games["price"]=df_games["price"].astype(str).str.replace(r'Play Now','None',regex=True)

In [272]:
df_games["price"].unique()

array(['4.99', '0', '0.99', '3.99', '18.99', '29.99', '10.99', '2.99',
       '1.5899999999999999', '14.99', '1.99', '59.99', '9.99', '6.99',
       '7.99', '39.99', '19.99', '7.49', '8.99', '12.99', '5.99', '2.49',
       '15.99', '1.25', '24.99', '17.99', '61.99', '3.49', '11.99',
       '13.99', 'None', '34.99', '1.49', '32.99', '99.99', '14.95',
       '69.99', '16.99', '79.99', '49.99', '13.98', '149.99', '771.71',
       '21.99', '89.99', '0.98', '139.92', '4.29', '54.99', '64.99',
       '74.99', '0.89', '0.5', '299.99', '1.29', '119.99', '44.99', '3.0',
       '15.0', '1.3900000000000001', '2.0', '4.0', '1.9500000000000002',
       '1.5', '6.66', '26.99', '399.99', '31.99', '20.0', '40.0', '5.0',
       '3.33', '38.85', '71.7', '995.0', '5.49', '27.49', '3.39', '6.0',
       '19.95', '20.99', '499.99', '27.99', '199.99', '4.68', '131.4',
       '44.98', '202.76', '2.3', '0.9500000000000001', '36.99', '172.24',
       '249.99', '2.9699999999999998', '10.96', '2.66', '6.48', '10.0',
       '1.0', '11.15', '49.0', '199.0', '99.0', '87.94', '0.49', '9.98',
       '9.95', '12.89', '6.49', '1.87', '41.99', '4.49', '289.99',
       '23.96', '5.65', '12.0', '129.99', '23.99', '13.37', '189.96',
       '59.95', '160.91'], dtype=object)

In [273]:
df_games["price"].replace("None",np.nan,inplace=True)

In [274]:
df_games["price"].unique()

array(['4.99', '0', '0.99', '3.99', '18.99', '29.99', '10.99', '2.99',
       '1.5899999999999999', '14.99', '1.99', '59.99', '9.99', '6.99',
       '7.99', '39.99', '19.99', '7.49', '8.99', '12.99', '5.99', '2.49',
       '15.99', '1.25', '24.99', '17.99', '61.99', '3.49', '11.99',
       '13.99', nan, '34.99', '1.49', '32.99', '99.99', '14.95', '69.99',
       '16.99', '79.99', '49.99', '13.98', '149.99', '771.71', '21.99',
       '89.99', '0.98', '139.92', '4.29', '54.99', '64.99', '74.99',
       '0.89', '0.5', '299.99', '1.29', '119.99', '44.99', '3.0', '15.0',
       '1.3900000000000001', '2.0', '4.0', '1.9500000000000002', '1.5',
       '6.66', '26.99', '399.99', '31.99', '20.0', '40.0', '5.0', '3.33',
       '38.85', '71.7', '995.0', '5.49', '27.49', '3.39', '6.0', '19.95',
       '20.99', '499.99', '27.99', '199.99', '4.68', '131.4', '44.98',
       '202.76', '2.3', '0.9500000000000001', '36.99', '172.24', '249.99',
       '2.9699999999999998', '10.96', '2.66', '6.48', '10.0', '1.0',
       '11.15', '49.0', '199.0', '99.0', '87.94', '0.49', '9.98', '9.95',
       '12.89', '6.49', '1.87', '41.99', '4.49', '289.99', '23.96',
       '5.65', '12.0', '129.99', '23.99', '13.37', '189.96', '59.95',
       '160.91'], dtype=object)

In [275]:
df_games["price"]=df_games["price"].astype("float64")

In [276]:
df_games["price"].unique()

array([4.9900e+00, 0.0000e+00, 9.9000e-01, 3.9900e+00, 1.8990e+01,
       2.9990e+01, 1.0990e+01, 2.9900e+00, 1.5900e+00, 1.4990e+01,
       1.9900e+00, 5.9990e+01, 9.9900e+00, 6.9900e+00, 7.9900e+00,
       3.9990e+01, 1.9990e+01, 7.4900e+00, 8.9900e+00, 1.2990e+01,
       5.9900e+00, 2.4900e+00, 1.5990e+01, 1.2500e+00, 2.4990e+01,
       1.7990e+01, 6.1990e+01, 3.4900e+00, 1.1990e+01, 1.3990e+01,
              nan, 3.4990e+01, 1.4900e+00, 3.2990e+01, 9.9990e+01,
       1.4950e+01, 6.9990e+01, 1.6990e+01, 7.9990e+01, 4.9990e+01,
       1.3980e+01, 1.4999e+02, 7.7171e+02, 2.1990e+01, 8.9990e+01,
       9.8000e-01, 1.3992e+02, 4.2900e+00, 5.4990e+01, 6.4990e+01,
       7.4990e+01, 8.9000e-01, 5.0000e-01, 2.9999e+02, 1.2900e+00,
       1.1999e+02, 4.4990e+01, 3.0000e+00, 1.5000e+01, 1.3900e+00,
       2.0000e+00, 4.0000e+00, 1.9500e+00, 1.5000e+00, 6.6600e+00,
       2.6990e+01, 3.9999e+02, 3.1990e+01, 2.0000e+01, 4.0000e+01,
       5.0000e+00, 3.3300e+00, 3.8850e+01, 7.1700e+01, 9.9500e+02,
       5.4900e+00, 2.7490e+01, 3.3900e+00, 6.0000e+00, 1.9950e+01,
       2.0990e+01, 4.9999e+02, 2.7990e+01, 1.9999e+02, 4.6800e+00,
       1.3140e+02, 4.4980e+01, 2.0276e+02, 2.3000e+00, 9.5000e-01,
       3.6990e+01, 1.7224e+02, 2.4999e+02, 2.9700e+00, 1.0960e+01,
       2.6600e+00, 6.4800e+00, 1.0000e+01, 1.0000e+00, 1.1150e+01,
       4.9000e+01, 1.9900e+02, 9.9000e+01, 8.7940e+01, 4.9000e-01,
       9.9800e+00, 9.9500e+00, 1.2890e+01, 6.4900e+00, 1.8700e+00,
       4.1990e+01, 4.4900e+00, 2.8999e+02, 2.3960e+01, 5.6500e+00,
       1.2000e+01, 1.2999e+02, 2.3990e+01, 1.3370e+01, 1.8996e+02,
       5.9950e+01, 1.6091e+02])

In [279]:
df_games["price"]=df_games["price"].round(2)

In [280]:
df_games.head(5)

             publisher  ...            developer
0            Kotoshiro  ...            Kotoshiro
1     Making Fun, Inc.  ...     Secret Level SRL
2         Poolians.com  ...         Poolians.com
3                 彼岸领域  ...                 彼岸领域
4  Trickjump Games Ltd  ...  Trickjump Games Ltd

[5 rows x 10 columns]

In [281]:
#Saving the final file
df_games.to_csv("games_cleaned.csv",index=False)